version: "2"
linters:
  default: none
  enable:
    - errcheck
    - goheader
    - govet
    - ineffassign
    - staticcheck
  settings:
    goheader:
      template: |-
        Copyright 2026 Angel Tomala-Reyes

        SPDX-License-Identifier: Apache-2.0
    errcheck:
      check-type-assertions: false
      exclude-functions:
        - (*github.com/onsi/gomega.GomegaWithT).Expect
        - (github.com/onsi/gomega.Expect)
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - errcheck
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
