linters:
  disable-all: true
  enable:
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign

linters-settings:
  errcheck:
    check-type-assertions: false

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
