// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go
//
// Generated by this command:
//
//	mockgen -source=interface.go -destination=../../internal/testutil/mock_refreshstore.go -package=testutil -mock_names=RefreshStore=MockRefreshStore
//

// Package testutil is a generated GoMock package.
package testutil

import (
	context "context"
	reflect "reflect"
	time "time"

	storage "github.com/aetomala/jwtauth/pkg/storage"
	gomock "go.uber.org/mock/gomock"
)

// MockRefreshStore is a mock of RefreshStore interface.
type MockRefreshStore struct {
	ctrl     *gomock.Controller
	recorder *MockRefreshStoreMockRecorder
	isgomock struct{}
}

// MockRefreshStoreMockRecorder is the mock recorder for MockRefreshStore.
type MockRefreshStoreMockRecorder struct {
	mock *MockRefreshStore
}

// NewMockRefreshStore creates a new mock instance.
func NewMockRefreshStore(ctrl *gomock.Controller) *MockRefreshStore {
	mock := &MockRefreshStore{ctrl: ctrl}
	mock.recorder = &MockRefreshStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRefreshStore) EXPECT() *MockRefreshStoreMockRecorder {
	return m.recorder
}

// Cleanup mocks base method.
func (m *MockRefreshStore) Cleanup(ctx context.Context) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Cleanup", ctx)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Cleanup indicates an expected call of Cleanup.
func (mr *MockRefreshStoreMockRecorder) Cleanup(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Cleanup", reflect.TypeOf((*MockRefreshStore)(nil).Cleanup), ctx)
}

// ListTokens mocks base method.
func (m *MockRefreshStore) ListTokens(ctx context.Context, cursor string, count int) ([]*storage.RefreshToken, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTokens", ctx, cursor, count)
	ret0, _ := ret[0].([]*storage.RefreshToken)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListTokens indicates an expected call of ListTokens.
func (mr *MockRefreshStoreMockRecorder) ListTokens(ctx, cursor, count any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTokens", reflect.TypeOf((*MockRefreshStore)(nil).ListTokens), ctx, cursor, count)
}

// ListTokensForAudience mocks base method.
func (m *MockRefreshStore) ListTokensForAudience(ctx context.Context, audience, cursor string, count int) ([]*storage.RefreshToken, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTokensForAudience", ctx, audience, cursor, count)
	ret0, _ := ret[0].([]*storage.RefreshToken)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListTokensForAudience indicates an expected call of ListTokensForAudience.
func (mr *MockRefreshStoreMockRecorder) ListTokensForAudience(ctx, audience, cursor, count any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTokensForAudience", reflect.TypeOf((*MockRefreshStore)(nil).ListTokensForAudience), ctx, audience, cursor, count)
}

// ListTokensForUser mocks base method.
func (m *MockRefreshStore) ListTokensForUser(ctx context.Context, userID, cursor string, count int) ([]*storage.RefreshToken, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTokensForUser", ctx, userID, cursor, count)
	ret0, _ := ret[0].([]*storage.RefreshToken)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListTokensForUser indicates an expected call of ListTokensForUser.
func (mr *MockRefreshStoreMockRecorder) ListTokensForUser(ctx, userID, cursor, count any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTokensForUser", reflect.TypeOf((*MockRefreshStore)(nil).ListTokensForUser), ctx, userID, cursor, count)
}

// Namespace mocks base method.
func (m *MockRefreshStore) Namespace() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Namespace")
	ret0, _ := ret[0].(string)
	return ret0
}

// Namespace indicates an expected call of Namespace.
func (mr *MockRefreshStoreMockRecorder) Namespace() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Namespace", reflect.TypeOf((*MockRefreshStore)(nil).Namespace))
}

// Retrieve mocks base method.
func (m *MockRefreshStore) Retrieve(ctx context.Context, tokenID string) (*storage.RefreshToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Retrieve", ctx, tokenID)
	ret0, _ := ret[0].(*storage.RefreshToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Retrieve indicates an expected call of Retrieve.
func (mr *MockRefreshStoreMockRecorder) Retrieve(ctx, tokenID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Retrieve", reflect.TypeOf((*MockRefreshStore)(nil).Retrieve), ctx, tokenID)
}

// Revoke mocks base method.
func (m *MockRefreshStore) Revoke(ctx context.Context, tokenID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Revoke", ctx, tokenID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Revoke indicates an expected call of Revoke.
func (mr *MockRefreshStoreMockRecorder) Revoke(ctx, tokenID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Revoke", reflect.TypeOf((*MockRefreshStore)(nil).Revoke), ctx, tokenID)
}

// RevokeAllForAudience mocks base method.
func (m *MockRefreshStore) RevokeAllForAudience(ctx context.Context, audience string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeAllForAudience", ctx, audience)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RevokeAllForAudience indicates an expected call of RevokeAllForAudience.
func (mr *MockRefreshStoreMockRecorder) RevokeAllForAudience(ctx, audience any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeAllForAudience", reflect.TypeOf((*MockRefreshStore)(nil).RevokeAllForAudience), ctx, audience)
}

// RevokeAllForUser mocks base method.
func (m *MockRefreshStore) RevokeAllForUser(ctx context.Context, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeAllForUser", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeAllForUser indicates an expected call of RevokeAllForUser.
func (mr *MockRefreshStoreMockRecorder) RevokeAllForUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeAllForUser", reflect.TypeOf((*MockRefreshStore)(nil).RevokeAllForUser), ctx, userID)
}

// RevokeAllForUserAndAudience mocks base method.
func (m *MockRefreshStore) RevokeAllForUserAndAudience(ctx context.Context, userID, audience string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeAllForUserAndAudience", ctx, userID, audience)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RevokeAllForUserAndAudience indicates an expected call of RevokeAllForUserAndAudience.
func (mr *MockRefreshStoreMockRecorder) RevokeAllForUserAndAudience(ctx, userID, audience any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeAllForUserAndAudience", reflect.TypeOf((*MockRefreshStore)(nil).RevokeAllForUserAndAudience), ctx, userID, audience)
}

// Store mocks base method.
func (m *MockRefreshStore) Store(ctx context.Context, tokenID, userID string, audience []string, expiresAt time.Time, metadata map[string]any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Store", ctx, tokenID, userID, audience, expiresAt, metadata)
	ret0, _ := ret[0].(error)
	return ret0
}

// Store indicates an expected call of Store.
func (mr *MockRefreshStoreMockRecorder) Store(ctx, tokenID, userID, audience, expiresAt, metadata any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Store", reflect.TypeOf((*MockRefreshStore)(nil).Store), ctx, tokenID, userID, audience, expiresAt, metadata)
}
