// Code generated by MockGen. DO NOT EDIT.
// Source: keystore.go
//
// Generated by this command:
//
//	mockgen -source=keystore.go -destination=../../internal/testutil/mock_keystore.go -package=testutil -mock_names=KeyStore=MockKeyStore
//

// Package testutil is a generated GoMock package.
package testutil

import (
	context "context"
	rsa "crypto/rsa"
	reflect "reflect"

	keymanager "github.com/aetomala/jwtauth/pkg/keymanager"
	gomock "go.uber.org/mock/gomock"
)

// MockKeyStore is a mock of KeyStore interface.
type MockKeyStore struct {
	ctrl     *gomock.Controller
	recorder *MockKeyStoreMockRecorder
	isgomock struct{}
}

// MockKeyStoreMockRecorder is the mock recorder for MockKeyStore.
type MockKeyStoreMockRecorder struct {
	mock *MockKeyStore
}

// NewMockKeyStore creates a new mock instance.
func NewMockKeyStore(ctrl *gomock.Controller) *MockKeyStore {
	mock := &MockKeyStore{ctrl: ctrl}
	mock.recorder = &MockKeyStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKeyStore) EXPECT() *MockKeyStoreMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockKeyStore) Delete(ctx context.Context, keyID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, keyID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockKeyStoreMockRecorder) Delete(ctx, keyID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockKeyStore)(nil).Delete), ctx, keyID)
}

// LoadAll mocks base method.
func (m *MockKeyStore) LoadAll(ctx context.Context) ([]*keymanager.StoredKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadAll", ctx)
	ret0, _ := ret[0].([]*keymanager.StoredKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadAll indicates an expected call of LoadAll.
func (mr *MockKeyStoreMockRecorder) LoadAll(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadAll", reflect.TypeOf((*MockKeyStore)(nil).LoadAll), ctx)
}

// LoadKey mocks base method.
func (m *MockKeyStore) LoadKey(ctx context.Context, keyID string) (*rsa.PrivateKey, *keymanager.KeyMetadata, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadKey", ctx, keyID)
	ret0, _ := ret[0].(*rsa.PrivateKey)
	ret1, _ := ret[1].(*keymanager.KeyMetadata)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// LoadKey indicates an expected call of LoadKey.
func (mr *MockKeyStoreMockRecorder) LoadKey(ctx, keyID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadKey", reflect.TypeOf((*MockKeyStore)(nil).LoadKey), ctx, keyID)
}

// Save mocks base method.
func (m *MockKeyStore) Save(ctx context.Context, keyID string, privateKey *rsa.PrivateKey, meta keymanager.KeyMetadata) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, keyID, privateKey, meta)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockKeyStoreMockRecorder) Save(ctx, keyID, privateKey, meta any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockKeyStore)(nil).Save), ctx, keyID, privateKey, meta)
}

// UpdateMetadata mocks base method.
func (m *MockKeyStore) UpdateMetadata(ctx context.Context, keyID string, meta keymanager.KeyMetadata) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMetadata", ctx, keyID, meta)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateMetadata indicates an expected call of UpdateMetadata.
func (mr *MockKeyStoreMockRecorder) UpdateMetadata(ctx, keyID, meta any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMetadata", reflect.TypeOf((*MockKeyStore)(nil).UpdateMetadata), ctx, keyID, meta)
}
