// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go
//
// Generated by this command:
//
//	mockgen -source=interface.go -destination=../../internal/testutil/mock_refreshstore.go -package=testutil -mock_names=RefreshStore=MockRefreshStore
//

// Package testutil is a generated GoMock package.
package testutil

import (
	reflect "reflect"
	time "time"

	storage "github.com/aetomala/jwtauth/pkg/storage"
	gomock "go.uber.org/mock/gomock"
)

// MockRefreshStore is a mock of RefreshStore interface.
type MockRefreshStore struct {
	ctrl     *gomock.Controller
	recorder *MockRefreshStoreMockRecorder
	isgomock struct{}
}

// MockRefreshStoreMockRecorder is the mock recorder for MockRefreshStore.
type MockRefreshStoreMockRecorder struct {
	mock *MockRefreshStore
}

// NewMockRefreshStore creates a new mock instance.
func NewMockRefreshStore(ctrl *gomock.Controller) *MockRefreshStore {
	mock := &MockRefreshStore{ctrl: ctrl}
	mock.recorder = &MockRefreshStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRefreshStore) EXPECT() *MockRefreshStoreMockRecorder {
	return m.recorder
}

// Cleanup mocks base method.
func (m *MockRefreshStore) Cleanup() (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Cleanup")
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Cleanup indicates an expected call of Cleanup.
func (mr *MockRefreshStoreMockRecorder) Cleanup() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Cleanup", reflect.TypeOf((*MockRefreshStore)(nil).Cleanup))
}

// Retrieve mocks base method.
func (m *MockRefreshStore) Retrieve(tokenID string) (*storage.RefreshToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Retrieve", tokenID)
	ret0, _ := ret[0].(*storage.RefreshToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Retrieve indicates an expected call of Retrieve.
func (mr *MockRefreshStoreMockRecorder) Retrieve(tokenID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Retrieve", reflect.TypeOf((*MockRefreshStore)(nil).Retrieve), tokenID)
}

// Revoke mocks base method.
func (m *MockRefreshStore) Revoke(tokenID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Revoke", tokenID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Revoke indicates an expected call of Revoke.
func (mr *MockRefreshStoreMockRecorder) Revoke(tokenID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Revoke", reflect.TypeOf((*MockRefreshStore)(nil).Revoke), tokenID)
}

// RevokeAllForUser mocks base method.
func (m *MockRefreshStore) RevokeAllForUser(userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeAllForUser", userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeAllForUser indicates an expected call of RevokeAllForUser.
func (mr *MockRefreshStoreMockRecorder) RevokeAllForUser(userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeAllForUser", reflect.TypeOf((*MockRefreshStore)(nil).RevokeAllForUser), userID)
}

// Store mocks base method.
func (m *MockRefreshStore) Store(tokenID, userID string, expiresAt time.Time, metadata map[string]any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Store", tokenID, userID, expiresAt, metadata)
	ret0, _ := ret[0].(error)
	return ret0
}

// Store indicates an expected call of Store.
func (mr *MockRefreshStoreMockRecorder) Store(tokenID, userID, expiresAt, metadata any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Store", reflect.TypeOf((*MockRefreshStore)(nil).Store), tokenID, userID, expiresAt, metadata)
}
