package keys

import (
	"context"
	"crypto/rsa"
	"errors"
	"regexp"
)

//go:generate mockgen -source=keystore.go -destination=../../internal/testutil/mock_keystore.go -package=testutil -mock_names=KeyStore=MockKeyStore

// StoredKey is the value returned by KeyStore.LoadAll. It carries both the private
// key and its associated metadata in a single unit so callers do not need to make
// separate calls to reconstruct a key pair.
type StoredKey struct {
	KeyID      string
	PrivateKey *rsa.PrivateKey
	Metadata   KeyMetadata
}

// KeyStore defines the persistence contract for RSA key pairs managed by Manager.
// Implementations store private keys and their metadata and must be safe for
// concurrent use.
//
// DiskKeyStore is the reference implementation. Alternative backends (e.g. Redis)
// can be provided to support distributed deployments. All methods are safe for
// concurrent use.
type KeyStore interface {
	// LoadAll returns every valid (non-expired) persisted key. It is called once
	// at startup to warm the Manager's in-memory cache. Returns an empty slice
	// when no keys are found — this is not an error.
	LoadAll(ctx context.Context) ([]*StoredKey, error)

	// Save persists a newly generated key pair and its metadata. The caller is
	// responsible for populating meta.ID and meta.CreatedAt before calling.
	// Returns ErrKeyStoreInvalidKeyID if keyID is not a valid UUID v4 string.
	// Returns the context error if the context is cancelled.
	Save(ctx context.Context, keyID string, privateKey *rsa.PrivateKey, meta KeyMetadata) error

	// UpdateMetadata overwrites the persisted metadata for an existing key. Used
	// during rotation to set ExpiresAt on the outgoing signing key.
	// Returns ErrKeyStoreInvalidKeyID if keyID is not a valid UUID v4 string.
	// Returns ErrKeyStoreKeyNotFound if keyID does not exist.
	UpdateMetadata(ctx context.Context, keyID string, meta KeyMetadata) error

	// LoadKey fetches the private key and metadata for the given key ID. Called
	// by Manager.GetPublicKey on a cache miss.
	// Returns ErrKeyStoreInvalidKeyID if keyID is not a valid UUID v4 string.
	// Returns ErrKeyStoreKeyNotFound if the key does not exist.
	LoadKey(ctx context.Context, keyID string) (*rsa.PrivateKey, *KeyMetadata, error)

	// Delete removes the key identified by keyID from the store. Called by
	// Manager.cleanupExpiredKeys. If the key does not exist, no error is returned.
	// Returns ErrKeyStoreInvalidKeyID if keyID is not a valid UUID v4 string.
	Delete(ctx context.Context, keyID string) error

	// Namespace returns the namespace this store is operating in. For Redis-backed
	// stores this matches the configured KeyPrefix. Implementations that do not
	// support namespacing return empty string.
	Namespace() string
}

// Sentinel errors for KeyStore operations.
var (
	ErrKeyStoreKeyNotFound  = errors.New("key not found in store")
	ErrKeyStoreInvalidKeyID = errors.New("invalid key ID")
)

// keyIDPattern matches the lowercase UUID v4 string produced by uuid.New().String(),
// e.g. "3a2b5c4d-1e2f-4a3b-8c9d-0e1f2a3b4c5d". All key IDs generated by Manager
// use this format. Characters outside this set (path separators, dots, whitespace)
// indicate a forged or malformed token header and are rejected at the KeyStore boundary.
var keyIDPattern = regexp.MustCompile(`^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$`)

// isValidKeyID reports whether keyID matches the UUID format used by Manager.
// Returns false for empty strings, whitespace, path traversal sequences, and
// any value that could not have been generated by uuid.New().String().
func isValidKeyID(keyID string) bool {
	return keyIDPattern.MatchString(keyID)
}
